service: sb-gcp

runtime: java
env: flex

runtime_config:
  jdk: openjdk8

handlers:
- url: /.*
  script: this field is required, but ignored

manual_scaling:
  instances: 1

health_check:
  enable_health_check: true
  check_interval_sec: 10
  unhealthy_threshold: 5
  healthy_threshold: 1

env_variables:
  SPRING_DATA_MONGODB_URI: mongodb://IP_1:27017,IP_2:27017,IP_3:27017/test?replicaSet=rs0